name: Main CI
on:
  push:

jobs:
  get-vars:
    uses: ./.github/workflows/nodevars.yml

  main:
    needs: get-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.get-vars.outputs.node-version }}
          cache: npm
      - name: Setup npm
        run: npm i -g npm@${{ needs.get-vars.outputs.npm-version }}
      - name: Cache node modules
        id: node_modules_cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: Install
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint check
        run: npm run lint
      - name: Test
        run: npm run test
